const COMMANDS = {
  COMMANDES_INFORMATIONS: {
    HELP: {
      name: "help",
      alias: ["h"],
      category: "Informations",
      description: "Donne la liste des commandes et leur utilitée si l'une d'elle est identifiée à la fin de la commande",
      usage: "<commande>",
      args: false,
      cooldown: false,
      permission: false,
      colorEmbed: "#0000FF",
    }
  },
  COMMANDES_GENERALS: {
    EIGHTBALL: {
      name: "8ball",
      alias: ["8b"],
      category: "Général",
      description: "Répond une réponse au hasard",
      usage: "<question>",
      args: true,
      cooldown: false,
      permission: false,
      colorEmbed: "#F4F4F4",
    },
    SUGGESTIONS: {
      name: "suggestion",
      alias: ["sugg"],
      category: "Général",
      description: "Donner des suggestion pour le serveur",
      usage: "<suggestion>",
      args: true,
      cooldown: false,
      permission: false,
      colorEmbed: "#F4F4F4",
    }
  },
  COMMANDES_MODERATEURS: {
    DELMSG: {
      name: "clear",
      alias: ["cls"],
      category: "Modération",
      description: "Supprimer des messages",
      usage: "<nombre>",
      args: true,
      cooldown: false,
      permission: ["KICK_MEMBERS"],
      colorEmbed: "#FF8000",
    },
    KICK: {
      name: "kick",
      alias: false,
      category: "Modération",
      description: "",
      usage: "<mention/id> <description>",
      args: true,
      cooldown: false,
      permission: ["KICK_MEMBERS"],
      colorEmbed: "#FF0000",
    },
    MUTE: {
      name: "mute",
      alias: false,
      category: "Modération",
      description: "Rendre muet un membre",
      usage: "<mention/id> <description>",
      args: true,
      cooldown: false,
      permission: ["KICK_MEMBERS"],
      colorEmbed: "#FF0000",
    },
    UNMUTE: {
      name: "unmute",
      alias: false,
      category: "Modération",
      description: "",
      usage: "<mention/id> <description>",
      args: true,
      cooldown: false,
      permission: ["KICK_MEMBERS"],
      colorEmbed: "#00FF00",
    },
    WARN: {
      name: "warn",
      alias: false,
      category: "Modération",
      description: "Reppoerter un membre",
      usage: "<mention/id> <raison>",
      args: true,
      cooldown: false,
      permission: ["VIEW_AUDIT_LOG"],
      colorEmbed: "#FF0000",
    },
    INFRACTION: {
      name: "infractions",
      alias: false,
      category: "Modération",
      description: "Donne les infraction d'un membre",
      usage: "<mention/id>",
      args: false,
      cooldown: false,
      permission: ["KICK_MEMBERS"],
      colorEmbed: "#0000FF",
    }
  },
  COMMANDES_ADMINISTRATEURS: {
    BAN: {
      name: "ban",
      alias: false,
      category: "Administrations",
      description: "Banni le membre mentionné",
      usage: "<mention/id> <description>",
      args: true,
      cooldown: false,
      permission: ["BAN_MEMBERS"],
      colorEmbed: "#FF0000",
    },
    UNBAN: {
      name: "unban",
      alias: false,
      category: "Administrations",
      description: "Débanni le membre id",
      usage: "<id> <description>",
      args: true,
      cooldown: false,
      permission: ["BAN_MEMBERS"],
      colorEmbed: "#00FF00",
    },
    LOCK: {
      name: "lock",
      alias: false,
      category: "Administration",
      description: "Bloquer le salon au membres du serveur",
      usage: false,
      args: false,
      cooldown: false,
      permission: ["BAN_MEMBERS"],
      colorEmbed: "#FF0000",
    },
    UNLOCK: {
      name: "unlock",
      alias: false,
      category: "Administration",
      description: "Débloquer le salon au membres du serveur",
      usage: false,
      args: false,
      cooldown: false,
      permission: ["BAN_MEMBERS"],
      colorEmbed: "#00FF00",
    },
    NUKE: {
      name: "nuke",
      alias: false,
      category: "Administration",
      description: "Nuke le channel où est effectué la commande",
      usage: false,
      args: false,
      cooldown: false,
      permission: ["BAN_MEMBERS"],
      colorEmbed: "#FF0000",
    },
    SONDAGES: {
      name: "sondage",
      alias: false,
      category: "Administration",
      description: "Créer un sondage",
      usage: "<titre (première ligne)> <description du sondage (saut de ligne à chaque proposition)>",
      args: true,
      cooldown: false,
      permission: ["ADMINISTRATOR"],
      colorEmbed: "#0068FF",
    },
    DELWARN: {
      name: "delwarn",
      alias: ["dw"],
      category: "Administration",
      description: "Supprimer le warn d'un utilisateur",
      usage: "<id du warn>",
      args: true,
      cooldown: false,
      permission: ["ADMINISTRATOR"],
      colorEmbed: "#FF8000",
    }
  }
};

exports.COMMANDS = COMMANDS;

/*
name: "",
alias: false,
category: "",
description: "",
usage: false,
args: false,
cooldown: false,
permission: false,
colorEmbed: "#",
*/